name = "NeutrinoTelescopes"
uuid = "ef384c05-3785-4474-8b09-e6d5e3a3b215"
authors = ["Christian Haack <christian.haack@tum.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
