set-resources:
    photon_tables:
        slurm_extra: "'--gres=gpu:a40:1'"
        clusters: "alex"
        partition: "a40"
    train_amp_model:
        slurm_extra: "'--gres=gpu:a40:1'"
        clusters: "alex"
        partition: "a40"
    train_time_model:
        slurm_extra: "'--gres=gpu:a40:1'"
        clusters: "alex"
        partition: "a40"