slurm: True
default-resources:
  - slurm_account=capn
  - runtime="300"
  - slurm_extra="gres=gpu:1"
restart-times: 2
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 600
jobs: 250
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: False
